version: '1.0.0'
name: data_platform
services:
  trino:
    ports:
      - "8081:8080"
    image: "trinodb/trino:410"
    hostname: trino
    volumes:
      - ./etc:/usr/lib/trino/etc:ro
      - ./catalog:/etc/trino/catalog
    networks:
      - data_platform_network

networks:
  data_platform_network:
    external: true
