version: '1.0.0'
name: data_platform
services:
  minio:
    image: quay.io/minio/minio:latest
    container_name: minio
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "0.0.0.0:9001:9001"
    environment:
      MINIO_ROOT_USER: adminMinio
      MINIO_ROOT_PASSWORD: adminMinio
    volumes:
      - minio_data:/data
    healthcheck:
      test: ["CMD", "mc", "ready", "local"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - data_platform_network

volumes:
  minio_data:
    driver: local

networks:
  data_platform_network:
    external: true